apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
{{ include "common.labels" . | indent 4 }}
  name: mysql
  namespace: {{ dig "global" "db" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  ports:
    - name: "mysql"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None
