apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
{{ include "common.labels" . | indent 4 }}
  name: redis
  namespace: {{ dig "global" "db" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis 
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
