apiVersion: v2
name: monitoring
version: 0.1.2
description: A grafana-based monitoring service for jambonz
home: https://jambonz.org
keywords:
  - voip 
  - cpaas 
  - webRTC 
  - sip 
  - rtp
maintainers: 
  - name: Dave Horton
    email: daveh@drachtio.org
sources: 
  - https://github.com/jambonz/helm-charts
  - https://github.com/jambonz/jambonz-infrastructure
