apiVersion: v1
entries:
  monitoring:
  - apiVersion: v2
    created: "2023-06-28T10:05:23.82252+01:00"
    description: A grafana-based monitoring service for jambonz
    digest: 2c09c76937b2145f0062d918c063534d985aad312fe27f61f52e584aa47404c9
    home: https://jambonz.org
    keywords:
    - voip
    - cpaas
    - webRTC
    - sip
    - rtp
    maintainers:
    - email: daveh@drachtio.org
      name: Dave Horton
    name: monitoring
    sources:
    - https://github.com/jambonz/helm-charts
    - https://github.com/jambonz/jambonz-infrastructure
    urls:
    - monitoring-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    created: "2023-06-28T10:05:23.82168+01:00"
    description: A grafana-based monitoring service for jambonz
    digest: 7a6ea9d8d2835e9f61b5f5f57d3dace8f85c743854e77742e9a8b38b0d4cf903
    home: https://jambonz.org
    keywords:
    - voip
    - cpaas
    - webRTC
    - sip
    - rtp
    maintainers:
    - email: daveh@drachtio.org
      name: Dave Horton
    name: monitoring
    sources:
    - https://github.com/jambonz/helm-charts
    - https://github.com/jambonz/jambonz-infrastructure
    urls:
    - monitoring-0.1.4.tgz
    version: 0.1.4
generated: "2023-06-28T10:05:23.819409+01:00"
