# mysql configuration
mysql: 
  image: mysql:5.7
  host: mysql 
  database: jambones
  user: jambones 
  storage: 10Gi

# redis configuration used by Node.js app that need to connect
redis: 
  image: redis:alpine
  host: redis 
  port: "6379"
