apiVersion: v1
kind: Service
metadata:
  labels:
    app: feature-server
{{ include "common.labels" . | indent 4 }}
  name: feature-server
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: sip
      port: 5060
      protocol: UDP
      targetPort: 5060
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: feature-server
  clusterIP: None
