{{- if .Values.global.kong.enabled }}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ratelimit
config:
  hour: 1000
  limit_by: ip
  second: 50
plugin: rate-limiting
{{- end}}
