{{- if .Values.global.kong.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-gateway
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "false"
    konghq.com/plugins: ratelimit
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  rules:      
    - http:
        paths:
        {{- if .Values.global.kong.useHostnames }}
          - path: /
        {{else}}
          - path: /api
        {{- end}}
            pathType: Prefix
            backend:
              service:
                name:  api-server
                port:
                  number: {{ .Values.api.httpPort }}
      {{- if .Values.global.kong.useHostnames }}
      host: {{ required "hostname for REST API" .Values.api.hostname }}
      {{- end}}

    - http:
        paths:
        {{- if .Values.global.kong.useHostnames }}
          - path: /
        {{else}}
          - path: /webapp
        {{- end}}
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 3001
      {{- if .Values.global.kong.useHostnames }}
      host: {{ required "hostname for webapp" .Values.webapp.hostname }}
      {{- end}}
{{- end}}
