{{- if .Values.global.kong.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kong-monitoring
  namespace: default
  labels:
    app: kong-monitoring
spec:
  selector:
    app.kubernetes.io/name: kong
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 8100
    targetPort: 8100
{{- end}}