apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbc-inbound
{{ include "common.labels" . | indent 4 }}
  name: sbc-inbound
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: app
      port: {{ .Values.sbcInbound.drachtioPort }}
      protocol: TCP
      targetPort: {{ .Values.sbcInbound.drachtioPort }}
  selector:
    app: sbc-inbound
  clusterIP: None
