apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: jambonz-sbc-sip
  labels:
    app: jambonz-sbc-sip
{{ include "common.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: jambonz-sbc-sip
  template:
    metadata:
      labels:
        app: jambonz-sbc-sip
    spec:
      nodeSelector:
        {{ .Values.sbc.sip.nodeSelector.label }}: {{.Values.sbc.sip.nodeSelector.value }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: {{ .Values.sbc.sip.toleration | quote }}
          operator: "Exists"
          effect: "NoSchedule"
      initContainers:
        - image: kanisterio/mysql-sidecar:0.40.0
          name: db-create-wait
          command:
            - sh 
            - -c 
            - |
              until mysql -u {{ .Values.mysql.user }} -D {{ .Values.mysql.database }} -h mysql.{{ default .Release.Namespace .Values.global.db.namespace }} -p${MYSQL_PASSWORD} --protocol=tcp -e "select count(*) from accounts";
              do 
                sleep 5
              done
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: MYSQL_PASSWORD
      containers:
        - name: drachtio
          image: drachtio/drachtio-server:latest
          imagePullPolicy: {{ default "IfNotPresent" .Values.drachtio.imagePullPolicy }}
          args: 
            - drachtio
            - --loglevel
            - {{ .Values.sbcSip.loglevel }}
            - --cloud-deployment
            - --sofia-loglevel
            - {{ .Values.sbcSip.sofiaLoglevel | quote }}
            - --homer
            - heplify-server.{{ default .Release.Namespace .Values.global.monitoring.namespace }}
            - --homer-id
            - {{ .Values.drachtio.homerId | quote }}
          env:
            - name: DRACHTIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: DRACHTIO_SECRET
            - name: SOFIA_SEARCH_DOMAINS
              value: "1"
            - name: CLOUD 
              value: {{ required "cloud provider name" .Values.cloud | quote }}
          ports:
            - containerPort: 9022
              protocol: TCP
            - containerPort: 5060
              protocol: UDP
            - containerPort: 5060
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/drachtio.conf.xml
              name: jambonz-sbc-sip-conf
              subPath: drachtio.conf.xml
        - name: sbc-options-handler
          image: {{ .Values.sbcOptionsHandler.image }}
          imagePullPolicy: Always 
          env:
            - name: NODE_ENV
              value: production
            - name: K8S 
              value: "1"
            - name: JAMBONES_MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: JAMBONES_MYSQL_HOST
              value: mysql.{{ default .Release.Namespace .Values.global.db.namespace }}
            - name: JAMBONES_MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: JAMBONES_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: MYSQL_PASSWORD
            - name: DRACHTIO_HOST
              value: 127.0.0.1
            - name: DRACHTIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: DRACHTIO_SECRET
      restartPolicy: Always
      volumes:
      - name: jambonz-sbc-sip-conf
        configMap:
          name: jambonz-sbc-sip-conf
          items:
          - key: drachtio.conf.xml
            path: drachtio.conf.xml