apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbc-sip
{{ include "common.labels" . | indent 4 }}
  name: sbc-sip
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: sip-udp
      port: 5060
      targetPort: 5060
      protocol: UDP
    - name: sip-tcp
      port: 5060
      targetPort: 5060
      protocol: TCP
  selector:
    app: jambonz-sbc-sip
  clusterIP: None
