apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbc-outbound
{{ include "common.labels" . | indent 4 }}
  name: sbc-outbound
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: app
      port: {{ .Values.sbcOutbound.drachtioPort }}
      protocol: TCP
      targetPort: {{ .Values.sbcOutbound.drachtioPort }}
  selector:
    app: sbc-outbound
  clusterIP: None
