apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbc-registrar
{{ include "common.labels" . | indent 4 }}
  name: sbc-registrar
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: app
      port: {{ .Values.sbcRegistrar.drachtioPort }}
      protocol: TCP
      targetPort: {{ .Values.sbcRegistrar.drachtioPort }}
  selector:
    app: sbc-register
  clusterIP: None
